server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgres://localhost:5432/postgres
    username: postgres
    password: 123
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090/realms/Soa
  datasource:
    driver-class-name: org.postgresql.Driver
